dataset: nuscenes
split: rotnuscenes
data_path: /users_data/haitman/Datasets/NUSCENES_KITTI
cache_data_path: /new_users_data/users/haitman/UMERegRobust_Repo/Data/kitti_benchmarks
batch_size: 1
corr_batch_size: 128
corr_ds: 1
corr_kernel_sigma: 1
corr_no_nksr: false
device: cuda:0
filter_by_ume_dist_cond: true
hungarian_matching_flag: false
max_pc_size: 35000
model_checkpoint_path: weights/nuscenes_coloring_best_checkpoint.pth
num_samples: 512
num_workers: 0
out_ch: 32
pc_corr_max_size: 10000
pc_size_for_hypothesis_sel: 10000
rtume_nn_max: 750
rtume_r_nn: 5
seed: 0
skip_invalid_entries_flag: true
tau: 0.05
ume_max_nn: 750
ume_min_nn: 300
ume_n_samples: 2500
ume_r_nn: 5
