dataset: nuscenes
batch_size: 8
cache_data_path: "" # change path to SEM preprocessed data
calc_inlear_ratio_eval: true
data_path: /users_data/haitman/Datasets/NUSCENES_KITTI
device: cuda:0
eval_batch_size: -1
eval_inlear_thr: 0.6
eval_num_kpts: 1000
lr: 0.0001
max_pc_size: 40000
num_epochs: 100
num_pw_samples: 512
num_workers: 8
out_channels: 32
output_path: outputs
pw_loss_weight: 0.5
random_seed: 0
reg_loss_cube_r: 30.0
reg_loss_intersection_thr: 0.75
reg_loss_weight: 0.25
resume_train_path: ''
run_name: Coloring
skip_invalid_entries: true
tau: 0.1
tau_ume: 0.1
tau_ume_neg: 0.1
train_size: -1
ume_loss_weight: 0.5
ume_max_nn: 750
ume_min_nn: 300
ume_n_samples: 256
ume_r_nn: 5
use_aug: true
use_reg_loss: true
use_ume_loss: true
val_size: -1
